// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: api-service.proto

package users

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IsAdminResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsAdmin       bool                   `protobuf:"varint,1,opt,name=isAdmin,proto3" json:"isAdmin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsAdminResponse) Reset() {
	*x = IsAdminResponse{}
	mi := &file_api_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsAdminResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsAdminResponse) ProtoMessage() {}

func (x *IsAdminResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsAdminResponse.ProtoReflect.Descriptor instead.
func (*IsAdminResponse) Descriptor() ([]byte, []int) {
	return file_api_service_proto_rawDescGZIP(), []int{0}
}

func (x *IsAdminResponse) GetIsAdmin() bool {
	if x != nil {
		return x.IsAdmin
	}
	return false
}

type UserRolesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserRoles     []string               `protobuf:"bytes,1,rep,name=user_roles,json=userRoles,proto3" json:"user_roles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserRolesResponse) Reset() {
	*x = UserRolesResponse{}
	mi := &file_api_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRolesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRolesResponse) ProtoMessage() {}

func (x *UserRolesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRolesResponse.ProtoReflect.Descriptor instead.
func (*UserRolesResponse) Descriptor() ([]byte, []int) {
	return file_api_service_proto_rawDescGZIP(), []int{1}
}

func (x *UserRolesResponse) GetUserRoles() []string {
	if x != nil {
		return x.UserRoles
	}
	return nil
}

type ResetPasswordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phone         string                 `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetPasswordRequest) Reset() {
	*x = ResetPasswordRequest{}
	mi := &file_api_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetPasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetPasswordRequest) ProtoMessage() {}

func (x *ResetPasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetPasswordRequest.ProtoReflect.Descriptor instead.
func (*ResetPasswordRequest) Descriptor() ([]byte, []int) {
	return file_api_service_proto_rawDescGZIP(), []int{2}
}

func (x *ResetPasswordRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

type UpdatePasswordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Password      []byte                 `protobuf:"bytes,1,opt,name=password,proto3" json:"password,omitempty"`
	UserUuid      []byte                 `protobuf:"bytes,2,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePasswordRequest) Reset() {
	*x = UpdatePasswordRequest{}
	mi := &file_api_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePasswordRequest) ProtoMessage() {}

func (x *UpdatePasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePasswordRequest.ProtoReflect.Descriptor instead.
func (*UpdatePasswordRequest) Descriptor() ([]byte, []int) {
	return file_api_service_proto_rawDescGZIP(), []int{3}
}

func (x *UpdatePasswordRequest) GetPassword() []byte {
	if x != nil {
		return x.Password
	}
	return nil
}

func (x *UpdatePasswordRequest) GetUserUuid() []byte {
	if x != nil {
		return x.UserUuid
	}
	return nil
}

type UpdateUserRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UserUuid         []byte                 `protobuf:"bytes,1,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"`
	Username         string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email            string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	ValidationStatus int64                  `protobuf:"varint,4,opt,name=validation_status,json=validationStatus,proto3" json:"validation_status,omitempty"`
	FirstName        string                 `protobuf:"bytes,5,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName         string                 `protobuf:"bytes,6,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Avatar           string                 `protobuf:"bytes,7,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Addresses        *Addresses             `protobuf:"bytes,8,opt,name=addresses,proto3" json:"addresses,omitempty"`
	Phone            string                 `protobuf:"bytes,9,opt,name=phone,proto3" json:"phone,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UpdateUserRequest) Reset() {
	*x = UpdateUserRequest{}
	mi := &file_api_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserRequest) ProtoMessage() {}

func (x *UpdateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return file_api_service_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateUserRequest) GetUserUuid() []byte {
	if x != nil {
		return x.UserUuid
	}
	return nil
}

func (x *UpdateUserRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UpdateUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UpdateUserRequest) GetValidationStatus() int64 {
	if x != nil {
		return x.ValidationStatus
	}
	return 0
}

func (x *UpdateUserRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *UpdateUserRequest) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *UpdateUserRequest) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *UpdateUserRequest) GetAddresses() *Addresses {
	if x != nil {
		return x.Addresses
	}
	return nil
}

func (x *UpdateUserRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

type SignUpResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserUuid      []byte                 `protobuf:"bytes,1,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignUpResponse) Reset() {
	*x = SignUpResponse{}
	mi := &file_api_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignUpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignUpResponse) ProtoMessage() {}

func (x *SignUpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignUpResponse.ProtoReflect.Descriptor instead.
func (*SignUpResponse) Descriptor() ([]byte, []int) {
	return file_api_service_proto_rawDescGZIP(), []int{5}
}

func (x *SignUpResponse) GetUserUuid() []byte {
	if x != nil {
		return x.UserUuid
	}
	return nil
}

type VerifyByPhoneRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phone         string                 `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	CheckPhrase   string                 `protobuf:"bytes,2,opt,name=check_phrase,json=checkPhrase,proto3" json:"check_phrase,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyByPhoneRequest) Reset() {
	*x = VerifyByPhoneRequest{}
	mi := &file_api_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyByPhoneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyByPhoneRequest) ProtoMessage() {}

func (x *VerifyByPhoneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyByPhoneRequest.ProtoReflect.Descriptor instead.
func (*VerifyByPhoneRequest) Descriptor() ([]byte, []int) {
	return file_api_service_proto_rawDescGZIP(), []int{6}
}

func (x *VerifyByPhoneRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *VerifyByPhoneRequest) GetCheckPhrase() string {
	if x != nil {
		return x.CheckPhrase
	}
	return ""
}

// SignUpRequest is
type SignUpRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to LoginType:
	//
	//	*SignUpRequest_Phone
	//	*SignUpRequest_Email
	LoginType     isSignUpRequest_LoginType `protobuf_oneof:"login_type"`
	Password      []byte                    `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignUpRequest) Reset() {
	*x = SignUpRequest{}
	mi := &file_api_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignUpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignUpRequest) ProtoMessage() {}

func (x *SignUpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignUpRequest.ProtoReflect.Descriptor instead.
func (*SignUpRequest) Descriptor() ([]byte, []int) {
	return file_api_service_proto_rawDescGZIP(), []int{7}
}

func (x *SignUpRequest) GetLoginType() isSignUpRequest_LoginType {
	if x != nil {
		return x.LoginType
	}
	return nil
}

func (x *SignUpRequest) GetPhone() string {
	if x != nil {
		if x, ok := x.LoginType.(*SignUpRequest_Phone); ok {
			return x.Phone
		}
	}
	return ""
}

func (x *SignUpRequest) GetEmail() string {
	if x != nil {
		if x, ok := x.LoginType.(*SignUpRequest_Email); ok {
			return x.Email
		}
	}
	return ""
}

func (x *SignUpRequest) GetPassword() []byte {
	if x != nil {
		return x.Password
	}
	return nil
}

type isSignUpRequest_LoginType interface {
	isSignUpRequest_LoginType()
}

type SignUpRequest_Phone struct {
	Phone string `protobuf:"bytes,1,opt,name=phone,proto3,oneof"`
}

type SignUpRequest_Email struct {
	Email string `protobuf:"bytes,2,opt,name=email,proto3,oneof"`
}

func (*SignUpRequest_Phone) isSignUpRequest_LoginType() {}

func (*SignUpRequest_Email) isSignUpRequest_LoginType() {}

// SignInRequest is
type SignInRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to LoginType:
	//
	//	*SignInRequest_Phone
	//	*SignInRequest_Email
	LoginType     isSignInRequest_LoginType `protobuf_oneof:"login_type"`
	Password      []byte                    `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignInRequest) Reset() {
	*x = SignInRequest{}
	mi := &file_api_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignInRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignInRequest) ProtoMessage() {}

func (x *SignInRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignInRequest.ProtoReflect.Descriptor instead.
func (*SignInRequest) Descriptor() ([]byte, []int) {
	return file_api_service_proto_rawDescGZIP(), []int{8}
}

func (x *SignInRequest) GetLoginType() isSignInRequest_LoginType {
	if x != nil {
		return x.LoginType
	}
	return nil
}

func (x *SignInRequest) GetPhone() string {
	if x != nil {
		if x, ok := x.LoginType.(*SignInRequest_Phone); ok {
			return x.Phone
		}
	}
	return ""
}

func (x *SignInRequest) GetEmail() string {
	if x != nil {
		if x, ok := x.LoginType.(*SignInRequest_Email); ok {
			return x.Email
		}
	}
	return ""
}

func (x *SignInRequest) GetPassword() []byte {
	if x != nil {
		return x.Password
	}
	return nil
}

type isSignInRequest_LoginType interface {
	isSignInRequest_LoginType()
}

type SignInRequest_Phone struct {
	Phone string `protobuf:"bytes,1,opt,name=phone,proto3,oneof"`
}

type SignInRequest_Email struct {
	Email string `protobuf:"bytes,2,opt,name=email,proto3,oneof"`
}

func (*SignInRequest_Phone) isSignInRequest_LoginType() {}

func (*SignInRequest_Email) isSignInRequest_LoginType() {}

type UserEmpty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserEmpty) Reset() {
	*x = UserEmpty{}
	mi := &file_api_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserEmpty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserEmpty) ProtoMessage() {}

func (x *UserEmpty) ProtoReflect() protoreflect.Message {
	mi := &file_api_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserEmpty.ProtoReflect.Descriptor instead.
func (*UserEmpty) Descriptor() ([]byte, []int) {
	return file_api_service_proto_rawDescGZIP(), []int{9}
}

type TokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         []byte                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenRequest) Reset() {
	*x = TokenRequest{}
	mi := &file_api_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenRequest) ProtoMessage() {}

func (x *TokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenRequest.ProtoReflect.Descriptor instead.
func (*TokenRequest) Descriptor() ([]byte, []int) {
	return file_api_service_proto_rawDescGZIP(), []int{10}
}

func (x *TokenRequest) GetToken() []byte {
	if x != nil {
		return x.Token
	}
	return nil
}

// TokenResponse is response with session JWT
type TokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         []byte                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenResponse) Reset() {
	*x = TokenResponse{}
	mi := &file_api_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenResponse) ProtoMessage() {}

func (x *TokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenResponse.ProtoReflect.Descriptor instead.
func (*TokenResponse) Descriptor() ([]byte, []int) {
	return file_api_service_proto_rawDescGZIP(), []int{11}
}

func (x *TokenResponse) GetToken() []byte {
	if x != nil {
		return x.Token
	}
	return nil
}

type UserGetter struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Getter:
	//
	//	*UserGetter_UserUuid
	//	*UserGetter_Email
	//	*UserGetter_Phone
	Getter        isUserGetter_Getter `protobuf_oneof:"getter"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserGetter) Reset() {
	*x = UserGetter{}
	mi := &file_api_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserGetter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserGetter) ProtoMessage() {}

func (x *UserGetter) ProtoReflect() protoreflect.Message {
	mi := &file_api_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserGetter.ProtoReflect.Descriptor instead.
func (*UserGetter) Descriptor() ([]byte, []int) {
	return file_api_service_proto_rawDescGZIP(), []int{12}
}

func (x *UserGetter) GetGetter() isUserGetter_Getter {
	if x != nil {
		return x.Getter
	}
	return nil
}

func (x *UserGetter) GetUserUuid() []byte {
	if x != nil {
		if x, ok := x.Getter.(*UserGetter_UserUuid); ok {
			return x.UserUuid
		}
	}
	return nil
}

func (x *UserGetter) GetEmail() string {
	if x != nil {
		if x, ok := x.Getter.(*UserGetter_Email); ok {
			return x.Email
		}
	}
	return ""
}

func (x *UserGetter) GetPhone() string {
	if x != nil {
		if x, ok := x.Getter.(*UserGetter_Phone); ok {
			return x.Phone
		}
	}
	return ""
}

type isUserGetter_Getter interface {
	isUserGetter_Getter()
}

type UserGetter_UserUuid struct {
	UserUuid []byte `protobuf:"bytes,1,opt,name=user_uuid,json=userUuid,proto3,oneof"`
}

type UserGetter_Email struct {
	Email string `protobuf:"bytes,2,opt,name=email,proto3,oneof"`
}

type UserGetter_Phone struct {
	Phone string `protobuf:"bytes,3,opt,name=phone,proto3,oneof"`
}

func (*UserGetter_UserUuid) isUserGetter_Getter() {}

func (*UserGetter_Email) isUserGetter_Getter() {}

func (*UserGetter_Phone) isUserGetter_Getter() {}

var File_api_service_proto protoreflect.FileDescriptor

const file_api_service_proto_rawDesc = "" +
	"\n" +
	"\x11api-service.proto\x12\aservice\x1a\x10api-models.proto\"+\n" +
	"\x0fIsAdminResponse\x12\x18\n" +
	"\aisAdmin\x18\x01 \x01(\bR\aisAdmin\"2\n" +
	"\x11UserRolesResponse\x12\x1d\n" +
	"\n" +
	"user_roles\x18\x01 \x03(\tR\tuserRoles\",\n" +
	"\x14ResetPasswordRequest\x12\x14\n" +
	"\x05phone\x18\x01 \x01(\tR\x05phone\"P\n" +
	"\x15UpdatePasswordRequest\x12\x1a\n" +
	"\bpassword\x18\x01 \x01(\fR\bpassword\x12\x1b\n" +
	"\tuser_uuid\x18\x02 \x01(\fR\buserUuid\"\xaa\x02\n" +
	"\x11UpdateUserRequest\x12\x1b\n" +
	"\tuser_uuid\x18\x01 \x01(\fR\buserUuid\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12+\n" +
	"\x11validation_status\x18\x04 \x01(\x03R\x10validationStatus\x12\x1d\n" +
	"\n" +
	"first_name\x18\x05 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x06 \x01(\tR\blastName\x12\x16\n" +
	"\x06avatar\x18\a \x01(\tR\x06avatar\x12/\n" +
	"\taddresses\x18\b \x01(\v2\x11.models.AddressesR\taddresses\x12\x14\n" +
	"\x05phone\x18\t \x01(\tR\x05phone\"-\n" +
	"\x0eSignUpResponse\x12\x1b\n" +
	"\tuser_uuid\x18\x01 \x01(\fR\buserUuid\"O\n" +
	"\x14VerifyByPhoneRequest\x12\x14\n" +
	"\x05phone\x18\x01 \x01(\tR\x05phone\x12!\n" +
	"\fcheck_phrase\x18\x02 \x01(\tR\vcheckPhrase\"i\n" +
	"\rSignUpRequest\x12\x16\n" +
	"\x05phone\x18\x01 \x01(\tH\x00R\x05phone\x12\x16\n" +
	"\x05email\x18\x02 \x01(\tH\x00R\x05email\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\fR\bpasswordB\f\n" +
	"\n" +
	"login_type\"i\n" +
	"\rSignInRequest\x12\x16\n" +
	"\x05phone\x18\x01 \x01(\tH\x00R\x05phone\x12\x16\n" +
	"\x05email\x18\x02 \x01(\tH\x00R\x05email\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\fR\bpasswordB\f\n" +
	"\n" +
	"login_type\"\v\n" +
	"\tUserEmpty\"$\n" +
	"\fTokenRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\fR\x05token\"%\n" +
	"\rTokenResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\fR\x05token\"e\n" +
	"\n" +
	"UserGetter\x12\x1d\n" +
	"\tuser_uuid\x18\x01 \x01(\fH\x00R\buserUuid\x12\x16\n" +
	"\x05email\x18\x02 \x01(\tH\x00R\x05email\x12\x16\n" +
	"\x05phone\x18\x03 \x01(\tH\x00R\x05phoneB\b\n" +
	"\x06getter2\xa1\x05\n" +
	"\vUserService\x12.\n" +
	"\n" +
	"CreateUser\x12\f.models.User\x1a\x12.service.UserEmpty\x120\n" +
	"\tCheckAuth\x12\x15.service.TokenRequest\x1a\f.models.User\x12A\n" +
	"\fGetUserRoles\x12\x15.service.TokenRequest\x1a\x1a.service.UserRolesResponse\x12=\n" +
	"\n" +
	"GetIsAdmin\x12\x15.service.TokenRequest\x1a\x18.service.IsAdminResponse\x12+\n" +
	"\x06UserBy\x12\x13.service.UserGetter\x1a\f.models.User\x126\n" +
	"\n" +
	"UpdateUser\x12\x1a.service.UpdateUserRequest\x1a\f.models.User\x12J\n" +
	"\x11VerifyUserByPhone\x12\x1d.service.VerifyByPhoneRequest\x1a\x16.service.TokenResponse\x129\n" +
	"\x06SignUp\x12\x16.service.SignUpRequest\x1a\x17.service.SignUpResponse\x12B\n" +
	"\rResetPassword\x12\x1d.service.ResetPasswordRequest\x1a\x12.service.UserEmpty\x12D\n" +
	"\x0eUpdatePassword\x12\x1e.service.UpdatePasswordRequest\x1a\x12.service.UserEmpty\x128\n" +
	"\x06SignIn\x12\x16.service.SignInRequest\x1a\x16.service.TokenResponseB\x11Z\x0fprotocols/usersb\x06proto3"

var (
	file_api_service_proto_rawDescOnce sync.Once
	file_api_service_proto_rawDescData []byte
)

func file_api_service_proto_rawDescGZIP() []byte {
	file_api_service_proto_rawDescOnce.Do(func() {
		file_api_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_service_proto_rawDesc), len(file_api_service_proto_rawDesc)))
	})
	return file_api_service_proto_rawDescData
}

var file_api_service_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_api_service_proto_goTypes = []any{
	(*IsAdminResponse)(nil),       // 0: service.IsAdminResponse
	(*UserRolesResponse)(nil),     // 1: service.UserRolesResponse
	(*ResetPasswordRequest)(nil),  // 2: service.ResetPasswordRequest
	(*UpdatePasswordRequest)(nil), // 3: service.UpdatePasswordRequest
	(*UpdateUserRequest)(nil),     // 4: service.UpdateUserRequest
	(*SignUpResponse)(nil),        // 5: service.SignUpResponse
	(*VerifyByPhoneRequest)(nil),  // 6: service.VerifyByPhoneRequest
	(*SignUpRequest)(nil),         // 7: service.SignUpRequest
	(*SignInRequest)(nil),         // 8: service.SignInRequest
	(*UserEmpty)(nil),             // 9: service.UserEmpty
	(*TokenRequest)(nil),          // 10: service.TokenRequest
	(*TokenResponse)(nil),         // 11: service.TokenResponse
	(*UserGetter)(nil),            // 12: service.UserGetter
	(*Addresses)(nil),             // 13: models.Addresses
	(*User)(nil),                  // 14: models.User
}
var file_api_service_proto_depIdxs = []int32{
	13, // 0: service.UpdateUserRequest.addresses:type_name -> models.Addresses
	14, // 1: service.UserService.CreateUser:input_type -> models.User
	10, // 2: service.UserService.CheckAuth:input_type -> service.TokenRequest
	10, // 3: service.UserService.GetUserRoles:input_type -> service.TokenRequest
	10, // 4: service.UserService.GetIsAdmin:input_type -> service.TokenRequest
	12, // 5: service.UserService.UserBy:input_type -> service.UserGetter
	4,  // 6: service.UserService.UpdateUser:input_type -> service.UpdateUserRequest
	6,  // 7: service.UserService.VerifyUserByPhone:input_type -> service.VerifyByPhoneRequest
	7,  // 8: service.UserService.SignUp:input_type -> service.SignUpRequest
	2,  // 9: service.UserService.ResetPassword:input_type -> service.ResetPasswordRequest
	3,  // 10: service.UserService.UpdatePassword:input_type -> service.UpdatePasswordRequest
	8,  // 11: service.UserService.SignIn:input_type -> service.SignInRequest
	9,  // 12: service.UserService.CreateUser:output_type -> service.UserEmpty
	14, // 13: service.UserService.CheckAuth:output_type -> models.User
	1,  // 14: service.UserService.GetUserRoles:output_type -> service.UserRolesResponse
	0,  // 15: service.UserService.GetIsAdmin:output_type -> service.IsAdminResponse
	14, // 16: service.UserService.UserBy:output_type -> models.User
	14, // 17: service.UserService.UpdateUser:output_type -> models.User
	11, // 18: service.UserService.VerifyUserByPhone:output_type -> service.TokenResponse
	5,  // 19: service.UserService.SignUp:output_type -> service.SignUpResponse
	9,  // 20: service.UserService.ResetPassword:output_type -> service.UserEmpty
	9,  // 21: service.UserService.UpdatePassword:output_type -> service.UserEmpty
	11, // 22: service.UserService.SignIn:output_type -> service.TokenResponse
	12, // [12:23] is the sub-list for method output_type
	1,  // [1:12] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_api_service_proto_init() }
func file_api_service_proto_init() {
	if File_api_service_proto != nil {
		return
	}
	file_api_models_proto_init()
	file_api_service_proto_msgTypes[7].OneofWrappers = []any{
		(*SignUpRequest_Phone)(nil),
		(*SignUpRequest_Email)(nil),
	}
	file_api_service_proto_msgTypes[8].OneofWrappers = []any{
		(*SignInRequest_Phone)(nil),
		(*SignInRequest_Email)(nil),
	}
	file_api_service_proto_msgTypes[12].OneofWrappers = []any{
		(*UserGetter_UserUuid)(nil),
		(*UserGetter_Email)(nil),
		(*UserGetter_Phone)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_service_proto_rawDesc), len(file_api_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_service_proto_goTypes,
		DependencyIndexes: file_api_service_proto_depIdxs,
		MessageInfos:      file_api_service_proto_msgTypes,
	}.Build()
	File_api_service_proto = out.File
	file_api_service_proto_goTypes = nil
	file_api_service_proto_depIdxs = nil
}
