syntax = "proto3";
package service;

option go_package = "protocols/users";

import "api-models.proto";

// UserService is
service UserService {
    rpc CreateUser(models.User) returns(UserEmpty);

    rpc CheckAuth(TokenRequest) returns(models.User);
    rpc GetUserRoles(TokenRequest) returns(UserRolesResponse);
    rpc GetIsAdmin(TokenRequest) returns(IsAdminResponse);
    rpc UserBy(UserGetter) returns(models.User);

    rpc UpdateUser(UpdateUserRequest) returns(models.User);
    rpc UpdateAddress(UpdateAddressRequest) returns(models.User);
    rpc AddAddresses(AddAddressesRequest) returns(models.User);

    rpc VerifyUserByPhone(VerifyByPhoneRequest) returns(TokenResponse);
    rpc SignUp(SignUpRequest) returns(SignUpResponse);

    rpc ResetPassword (ResetPasswordRequest) returns (UserEmpty);

    rpc UpdatePassword (UpdatePasswordRequest) returns (UserEmpty);
    // SignInRequest
    rpc SignIn(SignInRequest) returns(TokenResponse);

}

message IsAdminResponse{
    bool isAdmin = 1;
}
message UserRolesResponse {
    repeated string user_roles = 1;
}

message ResetPasswordRequest {
    string  phone   = 1;
}

message UpdatePasswordRequest {
    bytes   password    = 1;
    bytes   user_uuid        = 2;
}

message UpdateUserRequest {
    bytes       user_uuid                  = 1;
    string      username                   = 2;
    string      email                      = 3;
    int64       validation_status          = 4;
    string      first_name                 = 5;
    string      last_name                  = 6;
    string      avatar                     = 7;
    models.Addresses   addresses              = 8;
    string          phone                  = 9;
}
message AddAddressesRequest{
    bytes       user_uuid                  = 1;
    models.Addresses   addresses       = 2;
}
message UpdateAddressRequest{
    bytes       user_uuid                  = 1;
    models.Address address = 2;
}
message SignUpResponse{
    bytes user_uuid = 1;
}
message VerifyByPhoneRequest{
    string phone = 1;
    string check_phrase = 2;
}
// SignUpRequest is
message SignUpRequest {
    oneof login_type {
        string  phone   = 1;
        string  email   = 2;
    }
    bytes   password    = 3;
}

// SignInRequest is
message SignInRequest {
    oneof login_type {
        string  phone   = 1;
        string  email   = 2;
    }
    bytes   password    = 3;
}
message UserEmpty {}

message TokenRequest {
    bytes   token   = 1;
}

// TokenResponse is response with session JWT
message TokenResponse {
    bytes   token   = 1;
}

message UserGetter {
    oneof getter {
        bytes   user_uuid    = 1;
        string  email   = 2;
        string  phone = 3;
    }
}