syntax = "proto3";
package service;

option go_package = "protocols/users";

import "api-models.proto";

// UserService is
service UserService {
    rpc CreateUser(models.User) returns(UserEmpty);

    rpc CheckAuth(TokenRequest) returns(models.User);
    rpc UserBy(UserGetter) returns(models.User);

    rpc UpdateUser(UpdateUserRequest) returns(models.User);

    rpc SignUp(SignUpRequest) returns(SignUpResponse);
    // SignInRequest
    rpc SignIn(SignInRequest) returns(TokenResponse);

}

message UpdateUserRequest {
    bytes       user_uuid                  = 1;
    string      username                   = 2;
    string      email                      = 3;
    int64       validation_status          = 4;
    string      first_name                 = 5;
    string      last_name                  = 6;
    string      avatar                     = 7;
    repeated string addresses              = 8;
    string          phone                  = 9;
}
message SignUpResponse{
    bytes user_uuid = 1;
}
// SignUpRequest is
message SignUpRequest {
    oneof login_type {
        string  phone   = 1;
        string  email   = 2;
    }
    bytes   password    = 3;
}

// SignInRequest is
message SignInRequest {
    oneof login_type {
        string  phone   = 1;
        string  email   = 2;
    }
    bytes   password    = 3;
}
message UserEmpty {}

message TokenRequest {
    bytes   token   = 1;
}

// TokenResponse is response with session JWT
message TokenResponse {
    bytes   token   = 1;
}

message UserGetter {
    oneof getter {
        bytes   user_uuid    = 1;
        string  email   = 2;
        string  phone = 3;
    }
}